language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t tonyjwalt/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tonyjwalt/docker-react npm run test